### ISSUE TITLE
JS serialize binary error "Unknown base64 encoding at char: @"

### ISSUE THREAD

**Issue by dnovak270** [protocolbuffers/protobuf-javascript#172]
Create simple proto file:

```
syntax = "proto3";

message Test {
  bytes test_bytes_field = 1;
}
```

Generate code using buf:

```
# buf.gen.yaml
version: v1
plugins:
  - name: grpc-web
    out: ./src/grpc
    opt: import_style=commonjs+dts,mode=grpcwebtext
  - name: js
    out: ./src/grpc
    opt: import_style=commonjs,binary
```

Try setting a non base64 char (e.g. @) to test_bytes_field and use serializeBinary method on generated jspb.Message:

```
try {
  const test = new Test();
  test.setTestBytesField('@');
  test.serializeBinary();
} catch (e) {
  console.error({ e });
}
```
Results in an error  "Unknown base64 encoding at char: @"
